version: "3.9"

services:
  app:
    build:
      context: .
    volumes:
      - ./backend:/app
    ports:
      - "12345:8000"
    env_file:
      - .env
    restart: on-failure
    command: >
      sh -c "python manage.py wait_db && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
  db:
    image: mysql:8.0
    volumes:
      - ./mysql:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3309:3306"
    restart: on-failure

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./client:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf



#services:
#  db:
#    image: mysql:8.0
#    volumes:
#      - ./mysql:/var/lib/mysql
#    env_file:
#      - ./.env
#    ports:
#      - "3309:3306"
#    restart: on-failure