# Generated by Django 5.0.5 on 2024-05-14 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profilemodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profilemodel',
            table='profile',
        ),
    ]
