# Generated by Django 5.0.5 on 2024-05-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profilemodel_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='avatar',
            field=models.ImageField(default='', upload_to='avatar'),
            preserve_default=False,
        ),
    ]
