# Generated by Django 5.0.4 on 2024-05-02 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_carmodel_created_at_carmodel_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='price',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
