# Generated by Django 5.0.5 on 2024-05-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_remove_carmodel_chasis_remove_carmodel_engine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='price',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
