# Generated by Django 5.0.5 on 2024-05-10 06:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_parks', '0003_alter_autoparkmodel_user'),
        ('cars', '0008_carmodel_auto_park'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='chassis',
            field=models.CharField(choices=[('Hatchback', 'Hatchback'), ('Sedan', 'Sedan'), ('Coupe', 'Coupe'), ('Jeep', 'Jeep'), ('Wagon', 'Wagon')], default='Sedan', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='auto_park',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='auto_parks.autoparkmodel'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Z][a-zA-z]{2,49}$', ['first letter uppercase', 'min 3', 'max 50'])]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(9), django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2024)]),
        ),
    ]
