# Generated by Django 5.0.5 on 2024-05-14 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_carmodel_chassis_alter_carmodel_auto_park_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ('id',)},
        ),
    ]
