# Generated by Django 5.0.5 on 2024-05-14 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_parks', '0003_alter_autoparkmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoparkmodel',
            name='user',
        ),
    ]
