# Generated by Django 5.0.4 on 2024-04-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_rename_price_carmodel_seats_carmodel_chasis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='engine',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
